### ISSUE TITLE
자료조사

### ISSUE THREAD

**Issue by JINJUN941003** [Come-With-Me-SSAC/Monty-Hall-Problem-Simulation#1]
# Monty Hall Problem

 - [x] 몬티 홀 문제 찾아보기
 - [x] 관련 파이썬 코드 찾아보기

**Comment by CSung28** [comment]
https://smlee729.github.io/python/simulation/2015/04/28/1-monty-hall.html

몬티 홀 문제 홈페이지 입니다.
